---
driver:
  name: vagrant
  customize:
    memory: 1024
    cpus: 1

provisioner:
  name: chef_zero
  # You may wish to disable always updating cookbooks in CI or other testing environments.
  # For example:
  #   always_update_cookbooks: <%= !ENV['CI'] %>
  # always_update_cookbooks: true

verifier:
  name: inspec

platforms:
  - name: mycsc-7.4

suites:
  - name: ibmprs
    run_list:
      - recipe[ibmprs::do_prs]
    verifier:
      inspec_tests:
        - test/integration/default
    attributes:
